# LLM configurations
llm:
  default_model: 'claude-3-5-sonnet-20240620'
  models:
    - name: 'gpt-4-1106-preview'
      provider: 'openai'
      type: 'ChatOpenAI'
      temperature: 0.0
    - name: 'gpt-4o'
      provider: 'openai'
      type: 'ChatOpenAI'
      temperature: 0.0
    - name: 'claude-3-5-sonnet-20240620'
      provider: 'anthropic'
      type: 'ChatAnthropic'
      temperature: 0.0


# Task configurations
tasks:
  summary:
    primary: 'simple-rag:9388b291'
    additional: []
    label : 'Summary'
  alert:
    primary: 'simple-rag'
    additional: []
    label: 'Alert'
  actor_comparison:
    primary: 'rag-app'
    additional: []
    label: 'Actor Comparison'

# Comparison mode configuration
comparison_mode:
  enabled: true
  offer_models: ['gpt-4-1106-preview', 'GPT-4o-2024-05-13', 'claude-3-5-sonnet-20240620']

# Project indexes
project_indexes:
  dem-arm:
    - 'dem-arm-facebook'
    - 'dem-arm-telegram'
    - 'dem-arm-web'
    - 'dem-arm-youtube'
  dem-by:
    - 'dem-by-telegram'
    - 'dem-by-youtube'
    - 'dem-by-odnoklassniki'
    - 'dem-by-vkontakte'
    - 'dem-by-instagram'
    - 'dem-by-web'
    - 'dem-by-whisper-tiktok'

# Tally form configuration
tally_form:
  voting_id: 'w4LB6B'
  voting_width: 700
  voting_height: 800
  feedback_id: 'wzq1Aa'
  feedback_width: 700
  feedback_height: 800


# Date range configuration
date_range:
  default_start: null
  default_end: null
  min_date: '2020-01-01'

# Langchain configuration
langchain:
  tracing_v2: 'true'
  project: 'rag_app : summarization : production'
  endpoint: 'https://api.smith.langchain.com'

# Debug functionality
debug:
  display_source_texts: true

# KNN search params
max_doc_num : 30
num_candidates : 10000
