# LLM configurations
llm:
  default_model: 'claude-3-5-sonnet-20240620'
  models:
    - name: 'gpt-4-1106-preview'
      provider: 'openai'
      type: 'ChatOpenAI'
      temperature: 0.0
    - name: 'gpt-4o'
      provider: 'openai'
      type: 'ChatOpenAI'
      temperature: 0.0
    - name: 'claude-3-5-sonnet-20240620'
      provider: 'anthropic'
      type: 'ChatAnthropic'
      temperature: 0.0


# Task configurations
tasks:
  summary:
    primary: 'simple-rag:9388b291'
    additional: []
    label : 'Summary'
  alert:
    primary: 'simple-rag'
    additional: []
    label: 'Alert'
  actor_comparison:
    primary: 'rag-app'
    additional: []
    label: 'Actor Comparison'

# Comparison mode configuration
comparison_mode:
  enabled: true
  offer_models: ['gpt-4-1106-preview', 'GPT-4o-2024-05-13', 'claude-3-5-sonnet-20240620']

# Project indexes
project_indexes:
  dem-arm:
    - 'dem-arm-facebook'
    - 'dem-arm-telegram'
    - 'dem-arm-web'
    - 'dem-arm-youtube'
  dem-by:
    - 'dem-by-telegram'
    - 'dem-by-youtube'
    - 'dem-by-odnoklassniki'
    - 'dem-by-vkontakte'
    - 'dem-by-instagram'
    - 'dem-by-web'
    - 'dem-by-whisper-tiktok'
  'ua-by':
    - 'ua-by-facebook'
    - 'ua-by-telegram'
    - 'ua-by-web'
    - 'ua-by-youtube'
  'dm-8-countries':
    - 'dm-8-countries-twitter'
    - 'dm-8-countries-telegram'
  'recovery-win':
    - 'recovery-win-facebook'
    - 'recovery-win-telegram'
    - 'recovery-win-web'
    - 'recovery-win-twitter'
    - 'recovery-win-comments-telegram'
  'ru-balkans':
    - 'ru-balkans-facebook'
    - 'ru-balkans-telegram'
    - 'ru-balkans-youtube'
    - 'ru-balkans-sample-facebook'
    - 'ru-balkans-sample-telegram'
    - 'ru-balkans-sample-youtube'
  'arabic_test':
    - 'arabic-translation-test-web'
    - 'cs-disininfo-iq-telegram'
  'detector-media':
    - 'detector-media-tiktok'
  'eu4ge':
    - 'eu4ge-facebook'
    - 'eu4ge-web'
    - 'eu4ge-instagram'
    - 'eu4ge-telegram'
    - 'eu4ge-tiktok'

# Tally form configuration
tally_form:
  voting_id: 'w4LB6B'
  voting_width: 700
  voting_height: 800
  feedback_id: 'wzq1Aa'
  feedback_width: 700
  feedback_height: 800


# Date range configuration
date_range:
  default_start: null
  default_end: null
  min_date: '2020-01-01'

# Langchain configuration
langchain:
  tracing_v2: 'true'
  project: 'rag_app : summarization : production'
  endpoint: 'https://api.smith.langchain.com'

# Debug functionality
misc_display_options:
  display_source_texts: true
  display_topic_data: true
  display_issue_selector: true

# KNN search params
max_doc_num : 30
num_candidates : 10000
